apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-registry-flask-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harbor-registry-flask-test
  template:
    metadata:
      labels:
        app: harbor-registry-flask-test
    spec:
      imagePullSecrets:
        - name: my-harbor-secret
      containers:
        - name: harbor-registry-flask-test
          image: test/vdocker:latest
          ports:
            - containerPort: 8000
