apiVersion: v1
kind: Service
metadata:
  name: harbor-registry-flask-test
spec:
  type: NodePort
  selector:
    app: harbor-registry-flask-test
  ports:
    - nodePort: 8000
      port: 8000
      targetPort: 8000
